# Generated by Django 2.0.5 on 2018-06-02 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tensorflow_web', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelWithFileField',
        ),
    ]
